name: Build Rufus Linux
on: 
  push:
    branches: [ main ]
  workflow_dispatch: # ده اللي هيظهر لك زرار الـ Run يدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          pip install pyinstaller customtkinter packaging Pillow
          
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconsole main.py
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Rufus-for-Linux-App
          path: dist/
